name: Generate SBOM

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      attestations: write
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: CycloneDX .NET Generate SBOM
      uses: CycloneDX/gh-dotnet-generate-sbom@v1.0.1
      with:
        path: ./ch9_release/src/Tailwind.Traders.Web.sln
        github-bearer-token: ${{ secrets.GITHUB_TOKEN }}
        json: true
        
    - name: Attest
      uses: actions/attest-sbom@v1
      with:
        subject-path: ./ch9_release/src/Tailwind.Traders.Web/Dockerfile
        sbom-path: bom.json
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        path: bom.json
    
